language: cpp
compiler: 
- gcc
- clang
script:
- cd solver_application
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
- cmake --build _build --target install
- cd ..
- cd hello_world_application
- cmake .
- cmake --build 
addons:
apt:
sources:
- george-edison55-precise-backports
packages:
- cmake
- cmake-data
