language: cpp
compiler: 
- gcc
- clang
script:
- cd solver_application
- cmake .
- cmake --build
- cd ..
- cd hello_world_application
- cmake .
- cmake --build 
addons:
apt:
sources:
- george-edison55-precise-backports
packages:
- cmake
- cmake-data
